### ISSUE TITLE
Classifying widgets by different categories

### ISSUE THREAD

**Issue by suryaa62** [ACM-VIT/fludget#101]
Currently all types of widgets (layout , animation etc)  are in single page/list. it would be great if group same type of widgets, either in a single list or by listing different pages in app drawer(for example one layout menu in app drawer for all the layout widgets)

**Comment by AryanKhubchandani** [comment]
Hey @suryaa62, 
I had planned something similar once all the widgets would have been implemented, but I guess you can start working on this. I like the app drawer idea, can you showcase an example before you go ahead with that? I want to make sure we are on the same page before you implement it.
