### ISSUE TITLE
Implement AboutDialog Widget in the WIdget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#102]
AboutDialog Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in `homepage.dart` for better understanding. Showcase all properties including version, icon, legalese, 
Please attach screenshots of the same once done in the PR.

**Comment by sidheshwar-s** [comment]
Can you assign me this?

**Comment by AryanKhubchandani** [comment]
> Can you assign me this?

Sure, Good Luck!
