### ISSUE TITLE
Add Spacer Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#110]
Spacer Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in homepage.dart for better understanding. Use flex to show a customize layout to showcase a proper implementation of the widget.
Please attach screenshots of the same once done in your PR.

**Comment by sidheshwar-s** [comment]
Can you assign me this?

**Comment by sidheshwar-s** [comment]
> Update: A PR has been merged which has changed the location of the widget list from `homepage.dart` to `widgetList.dart`. Please make sure to keep that in mind and sync changes before opening a PR.

okay
