### ISSUE TITLE
Add Sizedbox Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#111]
SizedBox Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in `homepage.dart` for better understanding. Showcase various implementations including an empty sized box and a sized box having a child widget.
Please attach screenshots of the same once done in your PR.

**Comment by AryanKhubchandani** [comment]
> Hey!! I would like to work on this one. Can you assign me this ?

Sure, good luck!

**Comment by sachin161kr** [comment]
Hey ! .. I have implemented Sized Box Widget.  I am attaching the screenshots, check them out.

https://drive.google.com/drive/folders/1HpUnTBhioCq8R63AMlCduhLtnyfSayq6?usp=sharing

sizebox1.jpeg - Added an image as a child of sized box along with a button to change the dimensions when clicked.

sizebox2.jpeg - Added two containers separated by an empty sized box.
