### ISSUE TITLE
List of widgets should be on a different file

### ISSUE THREAD

**Issue by suryaa62** [ACM-VIT/fludget#115]
As i was doing changes in homepage.dart, I realised that the long list of widgets  comes in between that main code of homepage.dart. this list will go big with time only, it would be great if we will move the list to a different file which only contains this list.

**Comment by AryanKhubchandani** [comment]
> As i was doing changes in homepage.dart, I realised that the long list of widgets comes in between that main code of homepage.dart. this list will go big with time only, it would be great if we will move the list to a different file which only contains this list.

Yeah, makes sense. Do you want to work on this issue?

**Comment by suryaa62** [comment]
Yeah

**Comment by AryanKhubchandani** [comment]
> Yeah

Cool, I will assign it to you.
