### ISSUE TITLE
Implement StreamBuilder in the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#117]
StreamBuilder Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in homepage.dart for better understanding. Also add an argument for category of the widget and give it a category accordingly. Showcase proper implementation of the widget and feel free to have a creative approach.
Please attach a screen recording of the same once done in your PR.

**Comment by Kunal-8789** [comment]
@AryanKhubchandani Pls assign this issue to me.

**Comment by AryanKhubchandani** [comment]
> @AryanKhubchandani Pls assign this issue to me.

Sure, good luck!
