### ISSUE TITLE
Implement ScrollBar Widget in the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#131]
ScrollBar Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in `widgetList.dart` for better understanding. Also add an argument for category of the widget and give it a category accordingly. Implement both vertical and horizontal scroll bars and showcase various properties like isAlwaysShown, showTrack, etc.
Please attach a screen recording of the same once done in your PR.

**Comment by sidheshwar-s** [comment]
Can you assign me this?

**Comment by AryanKhubchandani** [comment]
> Can you assign me this?

Alright, I will assign it to you.
