### ISSUE TITLE
Refactor: Remove unused imports

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#140]
Some unused imports are present which need to be removed. Make sure there are no unintentional spaces/empty lines left once the imports have been removed.

**Comment by AryanKhubchandani** [comment]
> Hello @AryanKhubchandani, Can you please assign me this issue? I'll fix it

You can work on only one issue at a time. Please ask to get assigned to this issue once you are done with the previous one, provided this issue has not been addressed till then.

**Comment by Ashwith25** [comment]
Okay

**Comment by benardcharumbira** [comment]
@AryanKhubchandani may you please assign this to me

**Comment by AryanKhubchandani** [comment]
Due to inactivity, I am unassigning you from the issue @benardcharumbira
