### ISSUE TITLE
Implement SingleChildScrollView in the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#145]
SingleChildScrollView Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in `widgetList.dart` for better understanding. Also add an argument for category of the widget and give it a category accordingly. Showcase implementation both with and without using this widget to give a better idea of how this widget works.
Please attach screen shots of the same once done in the PR.

**Comment by AryanKhubchandani** [comment]
You basically need to show two implementations, one without this widget and one with this widget to showcase the advantage of using SingleChildScrollView.

**Comment by Aravind-Kannan** [comment]
@AryanKhubchandani I would like to take up this issue if there's no objection.
