### ISSUE TITLE
StreamBuilder Widget Model missing

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#154]
StreamBuilder Widget was built but the widget model is missing. Add the widget model in the `widgetList.dart' with all the attributes.

**Comment by AryanKhubchandani** [comment]
You can take this issue once your open PR has been merged and the issue has been solved. Hope you understand.

**Comment by sidheshwar-s** [comment]
> You can take this issue once your open PR has been merged and the issue has been solved. Hope you understand.

Sure man!

**Comment by AryanKhubchandani** [comment]
I will assign it to you now @sidheshwar-s, good luck!
