### ISSUE TITLE
Fix Light theme UI by removing/fixing hardcoded values

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#156]
There are few hardcoded values which need to be fixed for light theme UI. Here is a list of them:
- [x] WidgetDescription text in flexible.dart is hardcoded to white
- [x] Background color of CircularProgressIndicator Widget is hardcoded to white
- [x] Background color of LinearProgressIndicator Widget is hardcoded to white
- [x] Color of ListTile Widget is hardcoded to white
- [x] SliverAppBar Widget has its text and backgroundColor hardcoded to white
- [x] Text in StreamBuilder Widget is hardcoded to white
- [x] The buttons present in Wrap Widget are hardcoded to white

Make sure to make these colors dynamic using the ThemeData. Attach this checklist and the screenshots of the work once done in the PR.

**Comment by suryaa62** [comment]
Stream builder widget is not added in the list of widget.., should i add it? also what colors do you want for list tile?

**Comment by suryaa62** [comment]
so i should change color values in stream builder?
