### ISSUE TITLE
Enhancement: Add TabBar to all the widgets

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#16]
TabBar needs to be added to every widget present in the list. There should be 2 tabs, one for description of the widget and other for the implementation of the widget(which is already present).
For example, when you tap on column widget, the new page should have two tabs, one named 'Description' which describes what the column widget does and the other named 'Implementation' which shows the implementation of the widget. Since the implementation already exists, the same code needs to be added to this tab. This is supposed to be done for all the widgets present. 
Please share screenshots of the same..

**Comment by sj9102001** [comment]
Hey @AryanKhubchandani , please assign this issue to me!

**Comment by AryanKhubchandani** [comment]
> Hey @AryanKhubchandani , please assign this issue to me!

Sure, Good Luck!
