### ISSUE TITLE
Add TextField Widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#17]
TextField widget needs to be added to widget catalog. There should be two tabs within the page, one tab named "Description' to describe the widget and another tab named 'Implementation' to show the implementation of the widget. Please make sure all the implementations are present like number input, password input, etc. Please attach screenshots of your work in the PR.

**Comment by Kunal-8789** [comment]
I want to work upon this issue. Please assign this to me.

**Comment by AryanKhubchandani** [comment]
> @AryanKhubchandani I want to work upon this issue. Please assign this to me.

Sure, Good Luck!
