### ISSUE TITLE
Add ClipPath Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#176]
ClipPath Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in `widgetList.dart` for better understanding. Also add an argument for category of the widget and give it a category accordingly. Showcase all properties of the widget and show two implementations: one using clip and one without using clip. Try to use your creativity in using a custom path for the implementation.
Please attach screen shots of the same once done in your PR.

**Comment by sidheshwar-s** [comment]
Can you assign me this issue?
