### ISSUE TITLE
Add Dropdown Button widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#18]
DropdownButton widget needs to be added to the widget catalog. Please make sure that there are two tabs within the page, one tab named "Description' to describe the DropdownButton widget and another tab named 'Implementation' to show the implementation of the widget. Please make sure the implementation is proper and every example possible is showcased.
Please do attach screenshot of your work.

**Comment by Kunal-8789** [comment]
I want to learn drop-down and work upon this issue. Please assign it to me

**Comment by samyakjain26** [comment]
Please assign me this widget

**Comment by AryanKhubchandani** [comment]
> I want to learn drop-down and work upon this issue. Please assign it to me

Cool, I will assign it to you. All the best!

**Comment by AryanKhubchandani** [comment]
> Please assign me this widget

The issue is assigned on first come first serve basis, and someone had already requested before you. But don't worry, more issues will be opening soon!
