### ISSUE TITLE
Implement DecoratedBox Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#181]
DecoratedBox Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in `widgetList.dart` for better understanding. Also add an argument for category of the widget and give it a category accordingly. Showcase all properties of the widget. (Refer to the official docs in case of any doubts)
Please attach screen shots of the same once done in the PR.

**Comment by Aravind-Kannan** [comment]
I have worked on the issue. Please review my PR #191
