### ISSUE TITLE
Add Expanded Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#19]
Expanded widget needs to be added to widget catalog. There should be two tabs within the page, one tab named "Description' to describe the widget and another tab named 'Implementation' to show the implementation of the widget. Please make sure the implementation is done properly. For example, you can use Expanded Widget in a row or column to showcase its implementation. Also showcase the use of flex factor.
Please make sure to attach screen shots of the same.

**Comment by purushottam212** [comment]
hello , please assign this issue to me

**Comment by AryanKhubchandani** [comment]
> hello , please assign this issue to me

Sure, Good luck!

**Comment by purushottam212** [comment]
Thank You!! I will try my best..

**Comment by purushottam212** [comment]
hey added expanded widget can you check it please? let me know if any modifications are required..
Thanks
