### ISSUE TITLE
Add a dialog box widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#2]
The dialog box widget needs to be implemented in the application

**Comment by krish-dev-7** [comment]
can mention where should I add dialog widget? Thanks

**Comment by Nit89** [comment]
can I work on this? plz assign this to me

**Comment by DarthBenro008** [comment]
Hi @Nit89 , we already have a pending Pull Request for this issue, do watchout! we will be opening more issues!

cc: @AryanKhubchandani
