### ISSUE TITLE
Add Wrap Widget to the WIdget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#20]
Wrap widget needs to be added to widget catalog. There should be two tabs within the page, one tab named "Description' to describe the widget and another tab named 'Implementation' to show the implementation of the widget. Please make sure the implementation of alignment and spacing is also present. Please attach screenshot of the same in the PR.

**Comment by sj9102001** [comment]
hey, please assign this issue to me!

**Comment by AryanKhubchandani** [comment]
> hey, please assign this issue to me!

Alright, make sure to add the description of the widget in the description tab. Good luck!
