### ISSUE TITLE
Add Opacity widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#21]
Opacity Widget needs to be added to the widget catalog. There should be two tabs within the page, one tab named "Description' to describe the widget and another tab named 'Implementation' to show the implementation of the widget. Please make to include various implementations of the widget, including examples of different opacity values and blending using Stack. Make sure to explain the implementations. Please attach screenshot of your work for PR.

**Comment by samyakjain26** [comment]
Please assign me this widget

**Comment by AryanKhubchandani** [comment]
> Please assign me this widget

Sure, good luck! Make sure to include the description of the widget under the description tab and also that the backgroundColor is in accordance to the rest of the application.
