### ISSUE TITLE
Showcase the implementation of Table Widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#22]
Table widget needs to be added to the widget catalog. There should be two tabs within the page, one tab named "Description' to describe the widget and another tab named 'Implementation' to show the implementation of the widget. Please make sure that the implementation has all the different features of the widget like different alignments, widths and border. Please attach the screenshot of your work in the PR.

**Comment by Harshit-2000** [comment]
I would like to work on this widget.

**Comment by AryanKhubchandani** [comment]
> I would like to work on this widget.

Sure, I'll assign this issue to you. Good Luck!
