### ISSUE TITLE
Implement BottomNavigationBar Widget in the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#230]
BottomNavigationBar Widget needs to be added to the Widget Catalog. Read `How to contribute to the Widget Catalog` in the [README](https://github.com/ACM-VIT/fludget/blob/master/README.md) for detailed steps. Make sure to include all the arguments(name, implementation, description, codeString, link and category). Refer to any widget in `widgetList.dart` and its own `*widget*.dart` file for better understanding. Showcase all properties of the widget. (Refer to the official docs in case of any doubts)
Please attach screen recording of the same once done in the PR.

**Comment by yuran09** [comment]
Hi, I would like to contribute with this task, can you assign me?

**Comment by AryanKhubchandani** [comment]
You can work on only one issue at a time. You can ask to get assigned to this issue once you are done with issue you are working on right now provided no one else has been assigned to this issue till then.
