### ISSUE TITLE
Implement BackdropFilter Widget to the Widget List

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#236]
BackdropFilter Widget needs to be added to the Widget Catalog. Read `How to contribute to the Widget Catalog` in the [README](https://github.com/ACM-VIT/fludget/blob/master/README.md) for detailed steps. Make sure to include all the arguments(name, implementation, description, codeString, link and category). Refer to any widget in `widgetList.dart` and its own `*widget*.dart` file for better understanding. Showcase a variety of filters. (Refer to the official docs in case of any doubts)
Please attach screenshots of the same once done in the PR.

**Comment by Akshit97** [comment]
Thanks, I am working on this issue, in the meantime, I have raised PR for BottomNavigationBar Widget as well, #230
