### ISSUE TITLE
Enhancement: Add FloatingActionButton to all the widgets to open a link

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#25]
A FloatingActionButton needs to be added in the Description tab for all the widgets present in the Widget Catalog. The purpose of this button is to open a link to official documentation for that particular widget. For example, for text widget in Widget Catalog, a FloatingActionButton needs to be added in the description tab. On tapping the button, it should take you to the official documentation of the Text Widget (https://api.flutter.dev/flutter/widgets/Text-class.html is the link for this example). Make sure, this feature is properly implemented and not hard coded. Please attach screenshots for the same.

**Comment by RandyKdev** [comment]
Good day, I would like to have a go at this.

I donot really understand what is meant by hard coded in this context.
But here are the main actionable steps I would do to fix this: 

- Add a new member field called "link" in WidgetModel Class found in Models folder
- Edit all present calls to WidgetModel to include appropriate links
- Create new Widget which will be a wrapper to all present "sample widgets" which will contain the floating action button
- All sample widgets will be a child of the new widget created above

If this is good enough or atleast not hard coded, I would like to work on this.

**Comment by sj9102001** [comment]
@RandyKdev , you can directly pass the link through the constructor and add the floating action button in the following folder :
Routes/Root/rootScreen.dart
Just a suggestion, thanks.

**Comment by sj9102001** [comment]
S

**Comment by sj9102001** [comment]
SSS

**Comment by RandyKdev** [comment]
> Hello @RandyKdev , you can directly pass the link through the constructor and add the floating action button in the following folder : Routes/Root/rootScreen.dart Just a suggestion, thanks.

Yeah, I have updated my steps. Check it out. I didn't realize there was a root folder.
Thanks

**Comment by AryanKhubchandani** [comment]
> Good day, I would like to have a go at this.
> 
> I donot really understand what is meant by hard coded in this context. But here are the main actionable steps I would do to fix this:
> 
> * Add a new member field called "link" in WidgetModel Class found in Models folder
> * Edit all present calls to WidgetModel to include appropriate links
> * Edit rootScreen to include a floating action button and the onTap to that will open the link which will be passed from the homepage
> 
> If this is good enough or atleast not hard coded, I would like to work on this.

Sounds good to me, give it a try. All the best!
