### ISSUE TITLE
Add InteractiveViewer Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#250]
InteractiveViewer Widget needs to be added to the Widget Catalog. Read `How to contribute to the Widget Catalog` in the [README](https://github.com/ACM-VIT/fludget/blob/master/README.md) for detailed steps. Make sure to include all the arguments(name, implementation, description, codeString, link and category). Refer to any widget in `widgetList.dart` and its own `*widget*.dart` file for better understanding. Showcase all properties of the widget. (Refer to the official docs in case of any doubts)
Please attach screen recording of the same once done in the PR.

**Comment by Kunal-8789** [comment]
pls assign this to me.
