### ISSUE TITLE
Remove Cupertino Widget Section

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#317]
Cupertino Widget section needs to be removed. As only one tab will be left at the bottom, remove the BottomTabBar as well and make the changes accordingly. Change the Title of the App bar from 'Material Widget Catalog' to 'Widget Catalog'.

**Comment by AryanKhubchandani** [comment]
> @AryanKhubchandani Because Cupertino is Removed, can I remove files `materialwidgets.dart` and `cupertinowidgets.dart` and move in `homepage.dart`?

Yes please, but don’t include it in homepage, maybe have a different dart file and include the class in homepage

**Comment by deltarfd** [comment]
@AryanKhubchandani Okay I have finished it. Thank You
