### ISSUE TITLE
Add RichText Widget implementation

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#33]
RichText Widget implementation needs to be added to the Widget Catalog. Make sure that it is properly implemented under the Implementation tab and try to showcase all its properties. Description of the widget also needs to be added under the Description tab. Please share the screenshots of your work once done.

**Comment by babu1998** [comment]
I would like to take this up.

**Comment by AryanKhubchandani** [comment]
> I would like to take this up.

Sure, good luck!

**Comment by babu1998** [comment]
The PR for this issue is https://github.com/ACM-VIT/fludget/pull/60
