### ISSUE TITLE
Add ReorderableListView to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#34]
ReorderableListView needs to be added to the Widget Catalog. Make sure the implementation is done under the Implementation tab and description of the widget is added under the Description tab. Do share the screenshots of your work once done..

**Comment by RohanSengupta326** [comment]
@AryanKhubchandani  I would like to work on this. Please assign me.

**Comment by AryanKhubchandani** [comment]
> @AryanKhubchandani I would like to work on this. Please assign me.

Sure, good luck!

**Comment by RohanSengupta326** [comment]
@AryanKhubchandani I created the PR. Please check. Thank you.
