### ISSUE TITLE
Add ListTile Widget to the WIdget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#35]
ListTile Widget needs to be added to the Widget Catalog. Make sure the implementation is done under the Implementation tab and description of the widget is added under the Description tab. Make sure to include all the properties in your implementation including leading, trailing, title, subtitle, onTap, onLongPress, enabled, etc. Do share the screenshots of your work once done.

**Comment by samyakjain26** [comment]
assign me this widegt

**Comment by AryanKhubchandani** [comment]
> assign me this widegt

Alright! All the best!

**Comment by samyakjain26** [comment]
![Screenshot_20211005-224336](https://user-images.githubusercontent.com/79244707/136071164-07e598dd-04f2-488a-bfdf-429edf13a1ac.jpg)

**Comment by samyakjain26** [comment]
is it fine @AryanKhubchandani ?
