### ISSUE TITLE
Add DataTable Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#36]
DataTable Widget needs to be added to the Widget Catalog. Make sure the implementation is done under the Implementation tab and description of the widget is added under the Description tab. Make sure to include all the features of the DataTable Widget. Do share the screenshots of your work once done..

**Comment by AryanKhubchandani** [comment]
> I like to work on this , plz assign me

Sure, good luck!

**Comment by Nit89** [comment]
plz have a look
#44

**Comment by Nit89** [comment]
plz have a look at changes implemented #59
