### ISSUE TITLE
Add a card widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#4]
A card widget needs to be added to the widget catalog along with its different implementations

**Comment by Nit89** [comment]
I want to work on this issue plz assign me

**Comment by AryanKhubchandani** [comment]
> I want to work on this issue plz assign me

Sure, I will assign this issue to you. Make sure to include all possible implementations of a card widget. Good luck!

**Comment by Nit89** [comment]
I created a pull request ..plz have a look

**Comment by Nit89** [comment]
> I created a pull request ..plz have a look

#12

**Comment by Nit89** [comment]
plz have a look issue resolved #26
