### ISSUE TITLE
Enhancement: Add Dark theme and Light theme mode

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#40]
Implement a new feature of dark mode and option to switch between dark mode and light mode. The option to switch should be present in the settings menu which is present in the application. Please attach screenshots of your work once done in the PR. Hit me up incase of any doubt.

**Comment by umang-sinha** [comment]
I would like to take this up

**Comment by AryanKhubchandani** [comment]
> I would like to take this up

Sure! I'll assign it to you. Best of Luck!

**Comment by umang-sinha** [comment]
@AryanKhubchandani A lot of text colour values and background colour values inside the app have been hardcoded to white and grey[900] respectively which makes it really difficult to apply dynamic theming as the hard coded values override any colours declared in theme data. 
As of now, the only solution I can think of is to modify each and every instance of hard coded colour values which would be a very very tedious process. What do you suggest?

**Comment by AryanKhubchandani** [comment]
> @AryanKhubchandani A lot of text colour values and background colour values inside the app have been hardcoded to white and grey[900] respectively which makes it really difficult to apply dynamic theming as the hard coded values override any colours declared in theme data. As of now, the only solution I can think of is to modify each and every instance of hard coded colour values which would be a very very tedious process. What do you suggest?

I am aware of the hard coded values and it is a part of this issue to resolve this problem as well. I don't feel it will be as tedious, but if you have any concerns, do let me know.

**Comment by jushutch** [comment]
@umang-sinha Let me know if you want help with this, I'd be happy to work together!

**Comment by AryanKhubchandani** [comment]
Hey @umang-sinha, can you please update me regarding your progress with the issue?

**Comment by umang-sinha** [comment]
Hey, please assign this to someone else

**Comment by AryanKhubchandani** [comment]
> Hey, please assign this to someone else

Sure

**Comment by AryanKhubchandani** [comment]
@jushutch Let me know if you are interested in working on this issue.

**Comment by AryanKhubchandani** [comment]
> > @jushutch Let me know if you are interested in working on this issue.
> 
> I'd be happy to work on this issue!

Cool, I will assign it to you. Good luck!

**Comment by AryanKhubchandani** [comment]
@jushutch Can you update me with your progress?

**Comment by jushutch** [comment]
@AryanKhubchandani So far it's going well, I finished building the themes and implementing a toggle in the Settings menu and everything is working. Now I'm working on updating all of the pages to use the new themes, which is definitely taking the longest. I've attached screenshots below to show that the toggle is working. If you want, I could also push my branch with my progress so far so you could check it out locally. I'm hoping to finish the entire feature by the end of tomorrow. Let me know if you have any initial thoughts or feedback!

Screenshots:
![localhost_62089_(iPhone X) (3)](https://user-images.githubusercontent.com/44933935/136861263-36066ca3-c1f8-4b4e-92cf-49cad69567b4.png)
![localhost_62089_(iPhone X) (2)](https://user-images.githubusercontent.com/44933935/136861276-b77f070f-9784-405b-8908-9d3aa54a4f56.png)
![localhost_62089_(iPhone X) (1)](https://user-images.githubusercontent.com/44933935/136861281-9725d1ff-5f34-44ed-abb6-0fb70660345e.png)
![localhost_62089_(iPhone X)](https://user-images.githubusercontent.com/44933935/136861285-7e2a2b88-5e97-4036-a220-955cd06a244d.png)

**Comment by AryanKhubchandani** [comment]
Amazing @jushutch! The task was a little tedious, no doubt. But GG on being able to implement it properly!
