### ISSUE TITLE
Add a DraggableScrollableSheet Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#42]
DraggableScrollableSheet Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description Tab. Try to showcase all the features of the widget.
Please attach the screenshots of your work once done in the PR.

**Comment by dibyanshu-mohanty** [comment]
I can work on this widget

**Comment by AryanKhubchandani** [comment]
> I can work on this widget

You have already been assigned another issue, one can work at one issue at a time. Hit me up if this issue is still available once you have solved the other issue.

**Comment by sidheshwar-s** [comment]
Can i work on this issue?

**Comment by AryanKhubchandani** [comment]
> Can i work on this issue?

Sure, assigned. All the best!
