### ISSUE TITLE
Implement SnackBar Widget in the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#47]
SnackBar Widget needs to be added in the Widget Catalog. Make sure to include the description of the widget in the Description tab and the implementation is proper. 
Do attach the screenshots of your work once done.

**Comment by dibyanshu-mohanty** [comment]
I would like to work on this issue

**Comment by AryanKhubchandani** [comment]
> I would like to work on this issue

Cool, I will assign it to you. All the best!
