### ISSUE TITLE
Add a ListView.builder widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#5]
ListView.builder widget needs to be implemented in the application

**Comment by sj9102001** [comment]
Hey can this issue be assigned to me?

**Comment by sj9102001** [comment]
Hey, Please assign this issue to me!

**Comment by AryanKhubchandani** [comment]
> Hey, Please assign this issue to me!

Sure, you have been assigned to this issue.

**Comment by sj9102001** [comment]
Made a PR #10 to resolve this issue. please check and let me know.
