### ISSUE TITLE
Implement Hero Widget in the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#53]
Hero Widget needs to be implemented in the Widget Catalog. Make sure to include the description of the widget in the Description tab and the implementation is proper.
Please attach screenshots of the same once done in your PR.

**Comment by arcAman07** [comment]
Hey I would like to work on this issue

**Comment by AryanKhubchandani** [comment]
> Hey I would like to work on this issue

Someone is already working on this issue. But don't worry, new issues will be opening shortly. Make sure to keep an eye out for them!
