### ISSUE TITLE
Implement AbsorbPointer widget in the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#55]
AbsorbPointer Widget needs to be implemented in the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in `homepage.dart` for better understanding. Showcase the implementation properly using various clickable widgets. Make sure to also include a button in the end which can set absorbing property to false to showcase the usage of the widget. Hit me up incase of any doubt.
Please attach screenshots of the same once done in your PR.

**Comment by Saurabh65004** [comment]
Hey, I want to work on this, please assign it to me.  I have experience in Flutter.

**Comment by AryanKhubchandani** [comment]
> Hey, I want to work on this, please assign it to me. I have experience in Flutter.

Alright! All the best!

**Comment by Saurabh65004** [comment]
Thanks.

**Comment by AryanKhubchandani** [comment]
Hey @Saurabh65004, can you please update me regarding your progress?

**Comment by AryanKhubchandani** [comment]
@Saurabh65004 Due to inactivity, you are being unassigned from the issue.

**Comment by AryanKhubchandani** [comment]
@Kunal-8789 Let me know if you are still interested in working on this issue

**Comment by Kunal-8789** [comment]
@AryanKhubchandani yes I would work. Pls assign this to me .

**Comment by AryanKhubchandani** [comment]
Cool, good luck!
