### ISSUE TITLE
Add Dismissible Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#57]
Dismissible Widget needs to be implemented in the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in homepage.dart for better understanding. Showcase various implementations of the widget including different background colors, onDismissed property, secondary background, direction property, etc. You can showcase this on ListTiles. 
Please attach a screen recording of the same once done in your PR.

**Comment by vedantkulkarni** [comment]
Hi pls assign this to me

**Comment by AryanKhubchandani** [comment]
> Hi pls assign this to me

Sure, good luck!
