### ISSUE TITLE
Implement PageView Widget in the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#65]
PageView Widget needs to be implemented in the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in homepage.dart for better understanding.) Showcase the implementation properly and make sure each page is full of widgets so that the implementation makes sense. 
Please attach a screen recording of the same once done.

**Comment by samyakjain26** [comment]
Assign me this widget

**Comment by AryanKhubchandani** [comment]
> Assign me this widget

Sure, good luck!
