### ISSUE TITLE
Url launcher is not working 

### ISSUE THREAD

**Issue by sidheshwar-s** [ACM-VIT/fludget#67]
On the description page, you have a floating action button to take the user to the documentation. But it throws exception.

![image](https://user-images.githubusercontent.com/84003394/136149144-28537749-f3a9-4b91-a7b1-9e912072b9f4.png)

![image](https://user-images.githubusercontent.com/84003394/136149066-d47ae854-c16b-4a87-aca6-7b8ec9cf9a09.png)

**Comment by AryanKhubchandani** [comment]
Hey @sidheshwar-s, the links are working perfectly in my system, even for the DraggableScrollableSheet. I suggest you sync with the main branch and then run the following commands:
- Flutter clean
- Flutter get

Let me know if the issue still persists.
