### ISSUE TITLE
Enhancement: Add new implementations in Image Widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#70]
Certain new features need to be added to the Image Widget present in the Widget Catalog:
- [ ] There is an overflow error, so make the page scrollable
- [ ] Showcase the implementation of Image.file
- [ ] Showcase the implementation of Image.memory
- [ ] Add these two implementations in the subtitle of the list

Please attach screenshot of the same once done.

**Comment by sidheshwar-s** [comment]
> @sidheshwar-s Please make these additional changes as well

Okay!

**Comment by AryanKhubchandani** [comment]
@sidheshwar-s Please make sure to update the subtitle for ImageImplementation in `homepage.dart` as well.
