### ISSUE TITLE
Add CircularProgressIndicator Widget to the Widget Catalog

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#84]
LinearProgressIndicator Widget needs to be implemented in the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget. Showcase different variations if possible.
Please attach a screen recording of the same once done in your PR.

**Comment by suryaa62** [comment]
pls add me as assignee
