### ISSUE TITLE
Implement AnimatedList Widget

### ISSUE THREAD

**Issue by AryanKhubchandani** [ACM-VIT/fludget#86]
AnimatedList Widget needs to be added to the Widget Catalog. Make sure to include the description of the widget in the Description tab and add an argument to include link to the official docs of the widget (Refer to any example in `widgetList.dart` for better understanding. Showcase various animations while inserting or removing items.
Please attach a screen recording of the same once done in your PR.

**Comment by Nimish2000** [comment]
Hey @AryanKhubchandani  I  would like to work on it .

**Comment by AryanKhubchandani** [comment]
> @AryanKhubchandani Please assign this to me.

Alright, good luck!

**Comment by Nimish2000** [comment]
Sorry @AryanKhubchandani , My laptop ran into a problem so I was not able to update the work . Sorry for the trouble caused from my side.
